/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b1c9e6",
        "secondary-container": "#c7dffd",
        "surface-bright": "#f6fafe",
        "primary-fixed": "#d1e4ff",
        "on-tertiary-fixed-variant": "#005236",
        "outline": "#74777e",
        "on-secondary-container": "#4c637d",
        "surface-container-highest": "#dfe3e7",
        "inverse-primary": "#b0c9e8",
        "secondary-fixed": "#d0e4ff",
        "surface-container": "#eaeef2",
        "inverse-surface": "#2c3134",
        "on-error-container": "#93000a",
        "surface": "#f6fafe",
        "surface-dim": "#d6dade",
        "tertiary-container": "#00301e",
        "tertiary": "#00190e",
        "on-primary-fixed": "#011d35",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b0c9e8",
        "on-background": "#171c1f",
        "primary": "#00152a",
        "primary-container": "#102a43",
        "on-primary": "#ffffff",
        "outline-variant": "#c3c6ce",
        "on-surface": "#171c1f",
        "on-tertiary-fixed": "#002113",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#021d33",
        "inverse-on-surface": "#edf1f5",
        "on-primary-container": "#7a92b0",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#324861",
        "surface-container-low": "#f0f4f8",
        "on-surface-variant": "#43474d",
        "on-primary-fixed-variant": "#314863",
        "error": "#ba1a1a",
        "secondary": "#4a607a",
        "surface-variant": "#dfe3e7",
        "on-tertiary-container": "#00a472",
        "background": "#f6fafe",
        "surface-tint": "#49607c",
        "surface-container-high": "#e4e9ed",
        "tertiary-fixed-dim": "#4edea3",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}